name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NPM_GITHUB_ACCESS: ${{ secrets.NPM_GITHUB_ACCESS }}
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          envkey_REACT_APP_DEV_FEED_URL: ${{ secrets.DEV_FEED_URL }}
          envkey_REACT_APP_HOST_URL: ${{ secrets.HOST_URL }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test